##############################
# App Definition
app: video-highlight-cutter
component: highlight
core: autoeditor-video-or-audio
version: 1.0.2

##############################
# Definition of the Deployment
deployment:
  replicas: 1
  revisionHistoryLimit: 3
  sendlogs: "true"
  stack: syrin
  lbtype: internal
  affinity:
    - apps: services
  containers:
    - name: video-highlight-cutter
      image: ghcr.io/autoeditor-video-or-audio/
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "1Gi"
          cpu: "2"
      env:
        - name: TZ
          value: "America/Sao_Paulo"
        # sst
        - name: API_TRANSCRIBE_URL
          value: "whisper"
        - name: API_TRANSCRIBE_PORT
          value: "9000"
        - name: API_TRANSCRIBE_TIMEOUT
          value: "2400"
        # AI
        - name: OLLAMA_HOSTNAME
          value: "ollama"
        - name: OLLAMA_PORT
          value: "11434"
        - name: OLLAMA_MODEL
          value: "llama3.2:3b"
        - name: OLLAMA_TIMEOUT
          value: "2400"
        # Classificação de cortes
        - name: MIN_SCORE
          value: "5"

